name: SimpleCov Merge Action
description: Merges multiple simplecov resultsets to single result (and lcov)
author: mikian

inputs:
  coverage_path:
    description: Path for SimpleCov Resultset JSON files.
    required: false
    default: coverage/

outputs:
  json_path:
    description: Path to JSON coverage file
    value: ${{ steps.merge.outputs.json_path }}
  lcov_path:
    description: Path to LCov file
    value: ${{ steps.merge.outputs.lcov_path }}

runs:
  using: composite
  steps:
    - id: merge
      run: ruby ./merge.rb
      shell: bash
      env:
       COVERAGE_PATH: ${{ inputs.coverage_path }}
