name: SimpleCov Merge Action
description: Merges multiple simplecov resultsets to single result (and lcov)
author: mikian

inputs:
  coverage_path:
    description: Path for SimpleCov Resultset JSON files.
    required: false
    default: coverage/
  workspace:
    description: GitHub Workspace for normalising coverage paths
    required: false
    default: ${{ github.workspace }}

outputs:
  json_path:
    description: Path to JSON coverage file
  lcov_path:
    description: Path to LCov file

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    COVERAGE_PATH: ${{ inputs.coverage_path }}
    WORKSPACE: ${{ inputs.workspace }}
